use_frameworks!

platform :ios, '9.0'

target 'LRSAccelerometer_Example' do
  pod 'LRSAccelerometer', :path => '../'

  target 'LRSAccelerometer_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
